### ISSUE TITLE
No license added

### ISSUE THREAD

**Issue by shindouj** [TownEater/PropickFix#1]
Hi @TownEater,

Thanks for your work on this mod! I have noticed that your project does not include a license, and I would be potentially interested in making a fork of your mod - unless you intend to upkeep this project in the future.

Could you please either:
- add the license to this project,
- grant me an explicit permission to create a fork of this project re-licensed under GPL2?

I will understand if you will decline my request, of course.
Thanks a lot!

**Comment by TownEater** [comment]
Thank you for your interest in this mod! I went ahead and put an MIT license on it, I hope that is permissive enough for your purposes. I hope you can do some fun and interesting things with your fork! I may still do more on this in the future, but I have plenty of other mods I want to make too.
